#!/bin/bash
#
DATE=`date +"%Y%m%d_%H%M%S"`
mkdir -p /home/back/$DATE
cp -alr $1 /home/back/$DATE/ 
echo '------------------------------------'
echo ls " /home/back/$DATE/$1 " 
echo '------------------------------------'
ls /home/back/$DATE/$1


